explosivegaming/ExpCluster

StdLib/game.lua

Fixed most unlikely edgecase

---

config/preset_player_colours.lua

Because I'm lazy to do /color, I decided to do it here so I wouldn't have to do it ;P

Gave myself a colour

---

config/preset_player_colours.lua

Changed my color

---

config/chat_reply.lua
locale/en/addons.cfg

When "r!verify" is used a message will be printed to the player.

Added verify message

---

expcore/gui/prototype.lua

Filtered out gui elements without Gui.define

Fix Issue #149

---

config/_file_loader.lua
config/roles.lua
locale/en/commands.cfg
modules/gui/server-ups.lua

Added in game label to show the current server ups

Added Server UPS

---

modules/addons/station-auto-name.lua

fix for the problem that the img on the auto station namer would not work if placed next to oil

Fix for img type

---

expcore/commands.lua

- Cleaned up comments in commands module
- Made small performance improvements
- Fixed bug #105

Cleaned Up Commands

---

config/chat_reply.lua
config/expcore/command_general_parse.lua
config/expcore/command_role_parse.lua
config/expcore/permission_groups.lua
config/gui/player_list_actions.lua
expcore/external.lua
locale/en/gui.cfg
modules/addons/advanced-start.lua
modules/addons/chat-popups.lua
modules/addons/chat-reply.lua
modules/addons/compilatron.lua
modules/addons/death-logger.lua
modules/addons/discord-alerts.lua
modules/addons/scorched-earth.lua
modules/addons/spawn-area.lua
modules/addons/tree-decon.lua
modules/commands/clear-inventory.lua
modules/gui/player-list.lua
modules/gui/readme.lua
utils/game.lua

- Fixed discord alerts, inc. game time and titles.
- Added more info to discord alerts under server details.
- Fixed chat reply when using time based commands.
- Removed Game.get_player_by_index
- Removed over use of Game.get_player_from_any

Cleanup before master merge

---

modules/addons/station-auto-name.lua

Fixed the part that removes the ghost train staton key

---

config/gui/warps.lua
modules/control/warps.lua
modules/gui/warp-list.lua

Fixes #181
Also fixes that the warp tiles are left on the map because there is no radar coverage.

Changed choose_elem from item type to signal

---

modules/addons/fagc.lua

https://github.com/FactorioAntigrief/FactorioAntigrief/issues/124

Add ban and unban logging for FAGC clientside bot support

---

modules/factorio-control.lua

Add some missing functions to control.lua as some mod code errored due to them being missing.

Add some functions to control.lua

---

modules/commands/last-location.lua

it doesnt seem there is a need to display full gps location

1 decimal place on last location gps

---

modules/addons/tree-decon.lua

deconstruction of tree and rocks when drive over them

---

config/_file_loader.lua
config/expcore/roles.lua
modules/commands/artillery.lua

maybe there are some better ways to calculate how to reduce duplicates, but I haven't thought of one.

artillery target remote

---

modules/commands/artillery.lua

longer artillery flare lifetime

---

config/research.lua
modules/commands/research.lua

Adaptive Pollution Ageing

---

modules/data/personal-logistic.lua

Personal Logistic

---

config/module.lua

Module Inserter

---

.github/workflows/docs-deploy.yml
.github/workflows/pr-checker.yml
.luarc.json
config/chat_reply.lua
config/graftorio.lua
control.lua
docs/config.ld
expcore/async.lua
expcore/commands.lua
expcore/gui/left_flow.lua
expcore/gui/prototype.lua
expcore/gui/top_flow.lua
modules/addons/chat-reply.lua
modules/commands/warnings.lua
modules/control/jail.lua
modules/control/selection.lua
modules/control/warps.lua
modules/graftorio/forcestats.lua
modules/graftorio/general.lua
modules/graftorio/require.lua
modules/gui/debug/model.lua
modules/gui/vlayer.lua
modules/gui/warp-list.lua
overrides/debug.lua
overrides/table.lua
utils/game.lua
utils/task.lua

As title, switch to using a new linter that does not require a luacheckrc URL.

Use new linter

---

modules/gui/module.lua

Module GUI

---

modules/gui/production.lua

Production GUI

---

exp_scenario/module/commands/research.lua

when queue is 2, new queue is len 3, it should do level + 2, not level + 1.

Auto Research Queued Number

---

exp_legacy/module/config/vlayer.lua
exp_legacy/module/modules/gui/vlayer.lua

allow power for spaceship. less large ship means better ups.

vlayer space

---

exp_legacy/module/modules/gui/task-list.lua

EXP GUI Task List

---

exp_legacy/module/modules/gui/vlayer.lua

they should be able to just "see" the vlayer

GUI vlayer

---

exp_legacy/module/locale/en/data.cfg
exp_legacy/module/locale/zh-CN/data.cfg
exp_legacy/module/locale/zh-TW/data.cfg
exp_legacy/module/modules/gui/playerdata.lua

GUI PlayerData

---

exp_legacy/module/modules/control/vlayer.lua

combinator descr.
logistic filter.
fix delete section will cause issue.

Control vlayer

---

.github/workflows/fmtk.yml
exp_groups/module/module_exports.lua
exp_gui/module/data.lua
exp_gui/module/iter.lua
exp_legacy/module/expcore/permission_groups.lua
exp_scenario/module/commands/connect.lua
exp_util/module/module_exports.lua

PR created only so new workflow could be tested before merge.

Fix lint errors on new luals version

---

exp_legacy/module/config/research.lua
exp_legacy/module/modules/gui/research.lua
exp_scenario/module/commands/research.lua

I think it should be min not max.

Legacy GUI Research

---

exp_legacy/module/modules/addons/afk-kick.lua

As discussed, the logic should be reversed

Addon AFK Kick

---

exp_legacy/module/modules/control/protection.lua

Add space platform event to entity protection
