explosivegaming/ExpCluster

locale/Stand-Alone/Hex Map.lua
it doesn't matter what water generation is set to in the create map dialog, it will always remove it first
=> reorder tiles and stone creation, remove water first

Addons/Commands/repair.lua
I have...
- optimized /repair by making only one call to find entities and filtering out entities outside of the repair radius
- fixed repairing entities not sharing a force with the player which prevents healing enemies or trees/rocks
- fixed reviving ghosts which were placed by the player (not from being destroyed) which allowed for repairing technologies that were not researched or were otherwise unavailable
=> Fix repair command

StdLib/table.lua
This is used probably elsewhere but the warp list is the main place this error manifests whereby strings are sorted by ascii code rather than lexicographically. This is not wrong per se, but I do not think it was the intended behavior and the scenario gameplay is a bit impacted by the current sort order. This PR resolves the issue.
=> Fix logic error on table sort function

config/preset_player_colours.lua
"Sakama={r=20,g=213,b=80}" was printed twice, duplicate is removed.
=> Removed duplicate player's color

config/advanced_start.lua
Changed it to 10 mins as sometimes its really annoying when someone joins for 5 minutes doing nothing then leaves. Has happened a few times before and it just slows down progress massively
=> Changed cutoff time for furnaces and burners

modules/addons/advanced-start.lua
Fixed bug when advanced start would try to insert 0 item count into a players inventory.
=> Fix Spawn Items Equal 0

modules/addons/chat-popups.lua
Fixed issue with chat popup where players with - in the name would be seen as a lua string pattern.
=> Fixed chat popup for players with - in name

expcore/async.lua
Return `true` in async function to run again
=> Fix async module to allow recursive "async" functions

config/join_messages.lua, config/preset_player_colours.lua, modules/addons/greetings.lua
When a player joins a custom join message will be printed in chat for everyone to see. This message is set in the script after they have told us what message they want. Currently open for donators and staff.
=> Added Custom Join Messages

modules/data/quickbar.lua
=> Filter out `blueprint` and `blueprint-book` from quick bar player data

config/death_logger.lua, modules/addons/death-logger.lua
=> Corpse light and line addition

modules/control/warps.lua
This adds the ability to stay in your vehicle while warping.
Wanted to do this for ease of use with the Spidertron but it is not able to be teleported yet, I've submitted a bug report:
[bug report](https://forums.factorio.com/viewtopic.php?f=7&t=88128)
=> Added ability to warp while driving in a vehicle

modules/data/statistics.lua
When a player killed themselves with PvP enabled, the game couldn't access the player. This fixes it.
=> Fix of player not being valid when killing themselves

config/_file_loader.lua, config/gui/player_list_actions.lua, locale/en/addons.cfg, locale/en/commands.cfg, modules/addons/report-jail.lua, modules/commands/reports.lua, modules/control/reports.lua, modules/gui/player-list.lua
Reports will automatically jail a player after the combined player time of reporters exceeds 150% of the reported player's playtime. Also fixes empty reason strings, double output for admins and self reporting.
=> Auto jail for reports and other fixes

config/_file_loader.lua, config/expcore/roles.lua, locale/en/commands.cfg, modules/commands/search.lua
Added four commands which can be used to search the inventories of all players. The commands will display the top five players following 3 sort functions (the fouth command limits the 3rd to online only). These functions are based on: item count, join time, item count with play time.
=> Inventory Search Commands

modules/addons/discord-alerts.lua
Fixed a bug with all embed fields being inline. Also added a player's warning and report count to the respective embeds.
=> Report and warning count on embeds

locale/en/gui.cfg, modules/addons/tree-decon.lua
Added a button in the top left bar to toggle between fast decon mode and normal decon mode. Requires #217 to be merged to function properly and show the button to only those who have the `fast-tree-decon` permission.
=> Added a button to toggle fast decon mode

modules/addons/tree-decon.lua
Actually check whether a user has the tree decon enabled/disabled before adding the entity to the decon queue.
=> Fix tree decon toggle not working

expcore/common.lua, modules/addons/death-logger.lua, modules/addons/inventory-clear.lua, modules/commands/clear-inventory.lua
Fixed an issue where items would be transferred only by name and "copied", which would cause issues with items with metadata, for example contents of power armor.
=> Fix transfer of items after death and ban

config/_file_loader.lua, config/expcore/roles.lua, config/nukeprotect.lua, expcore/common.lua, locale/en/addons.cfg, modules/addons/nukeprotect.lua
Changed _C.move_items* to be _C.copy_items_stack, which copies items, and _C.move_items_stack, which moves items.
Added an addon called `nukeprotect`, which prevents players without a flag from having specific items in their inventories.
=> Implement nuke protect, fix move_items

modules/gui/autofill.lua
Fixed the issue with auto fill amounts not updating as a result of not finding the entity name.
=> Fixed auto fill amounts not working

config/nukeprotect.lua, modules/addons/nukeprotect.lua
This PR disables nukes completely by disabling the research for them (configgable), as they don't have much of real use besides griefers using them.
=> Disable nukes completely

modules/control/spectate.lua
Fixes the issue of spawning a new character when spectate is stopped while follow is active. This was caused by the following logic path:
1) `stop_spectate` would return you to your orginal body.
2) `on_tick` for follow would see you had a character and attempt to stop itself with `stop_follow`
3) Because `start_spectate` was successful in `start_follow` it assumes that `stop_spectate` needs to be called.
4) However, because it has already been called once it now has no reference to your character, this triggers a respawn.
5) Respawning disconnects your orginal body and gives you a new one.
=> Fix #279: Add spectate check to stop_follow

exp_scenario/module/commands/research.lua
since it only need 4 bottles, it should no longer require rocket launch
=> Auto research

exp_legacy/module/modules/addons/compilatron.lua
Error while running event level::on_nth_tick(900)
value for required field 'position' is missing
[C]: in function 'create_entity'
__level__/modules/exp_legacy/modules/addons/compilatron.lua:98: in function 'spawn_compilatron'
__level__/modules/exp_legacy/modules/addons/compilatron.lua:47: in function 'handler'
=> Compilatron

exp_util/module/module_exports.lua
Error while running event level::on_character_corpse_expired (ID 103)
__level__/modules/exp_util/module_exports.lua:423: attempt to index local 'entity' (a nil value)
__level__/modules/exp_util/module_exports.lua:423: in function 'get_storage_for_stack'
__level__/modules/exp_util/module_exports.lua:462: in function 'copy_items_to_surface'
__level__/modules/exp_util/module_exports.lua:495: in function 'transfer_inventory_to_surface'
...vel__/modules/exp_legacy/modules/addons/death-logger.lua:155: in function 'handler'
__level__/modules/exp_legacy/utils/event.lua:22: in function 'handler'
__core__/lualib/event_handler.lua:47: in function <__core__/lualib/event_handler.lua:45>
=> Module Exports

exp_legacy/module/config/vlayer.lua, exp_legacy/module/locale/en/gui.cfg, exp_legacy/module/locale/zh-CN/gui.cfg, exp_legacy/module/locale/zh-TW/gui.cfg, exp_legacy/module/modules/gui/vlayer.lua
some thinking on research balancing
=> vlayer power on space

exp_legacy/module/modules/addons/tree-decon.lua
Error while running event level::on_gui_click (ID 1)
LuaPlayer doesn't contain key player_index.
[C]: in function '__index'
__level__/modules/exp_gui/control.lua:40: in function 'get_player'
__level__/modules/exp_legacy/modules/addons/tree-decon.lua:47: in function 'handler'
__level__/modules/exp_gui/prototype.lua:406: in function 'raise_event'
__level__/modules/exp_gui/prototype.lua:391: in function 'handler'
__core__/lualib/event_handler.lua:47: in function <__core__/lualib/event_handler.lua:45>
=> EXP GUI Tree Decon

exp_scenario/module/commands/research.lua
The scenario level caused a non-recoverable error.
Please report this error to the scenario author.
Error while running event level::on_research_finished (ID 21)
__level__/modules/exp_scenario/commands/research.lua:74: attempt to index field '?' (a nil value)
__level__/modules/exp_scenario/commands/research.lua:74: in function 'handler'
__core__/lualib/event_handler.lua:47: in function <__core__/lualib/event_handler.lua:45>
=> Command Research

exp_legacy/module/modules/control/selection.lua
Please report this error to the scenario author.
Error while running event level::on_gui_click (ID 1)
No character.
[C]: in function '__index'
__level__/modules/exp_legacy/modules/control/selection.lua:79: in function 'start'
__level__/modules/exp_legacy/modules/gui/vlayer.lua:407: in function 'handler'
__level__/modules/exp_gui/prototype.lua:406: in function 'raise_event'
__level__/modules/exp_gui/prototype.lua:391: in function 'handler'
__core__/lualib/event_handler.lua:47: in function <__core__/lualib/event_handler.lua:45>
92.720 Error ServerMultiplayerManager.cpp:84: MultiplayerManager failed: "The scenario level caused a non-recoverable error.
=> Legacy Control Selection

exp_scenario/module/commands/trains.lua
This make the use of wagon as chest possible as it no longer set the train into automatic
=> Command Train

exp_legacy/module/modules/addons/spawn-area.lua
RCON ran for 18k ticks when nobody is online, there will be an error.
```
18014.527 Error ServerMultiplayerManager.cpp:84: MultiplayerManager failed: "The scenario level caused a non-recoverable error.
Please report this error to the scenario author.
Error while running event level::on_nth_tick(18000)
Unknown force: spawn
[C]: in function 'create_entity'
__level__/modules/exp_legacy/modules/addons/spawn-area.lua:47: in function 'spawn_turrets'
__level__/modules/exp_legacy/modules/addons/spawn-area.lua:197: in function 'handler'
__level__/modules/exp_legacy/utils/event.lua:22: in function 'handler'
__core__/lualib/event_handler.lua:81: in function <__core__/lualib/event_handler.lua:79>"
```
=> Spawn Area

exp_legacy/module/modules/control/vlayer.lua
Where [LuaLogisticsSection.set_slot](https://lua-api.factorio.com/latest/classes/LuaLogisticSection.html#set_slot) used to error when a filter already existed, it now returns the index allowing us to clear and reapply.
Closes: #388
=> Reattempt set slot after filter fail

exp_commands/module/commands/ipc.lua, exp_commands/module/commands/rcon.lua, exp_legacy/module/control.lua, exp_legacy/module/utils/event.lua, exp_util/module/async.lua, exp_util/module/include/package.lua, exp_util/module/storage.lua
Rather than using the clusterio startup event, this changes all occurrences to use the singleplayer and multiplayer init events that are called when a save first enters runtime.
=> Switch to singleplayer / multiplayer init events

exp_server_ups/instance.ts
When the last online player leaves, the update interval is paused to prevent commands being sent to the server. This prevents the slow crawl of 2ups servers even when paused.
=> Pause server ups when no players online
